function varargout = gmm(X, K_or_centroids)
% ============================================================
% Expectation-Maximization iteration implementation of
% Gaussian Mixture Model.
%
% How to call 
% PX = GMM(X, K_OR_CENTROIDS)
% or
% [PX MODEL] = GMM(X, K_OR_CENTROIDS)
% 
% INPUT:
% - X: N-by-D data matrix.
% - K_OR_CENTROIDS: either K indicating the number of 
%                   components or a K-by-D matrix indicating the
%                   choosing of the initial K centroids.
%
% OUTPUT:
%  - PX: N-by-K matrix indicating the probability of each
%        component generating each point.
%  - MODEL: a structure containing the parameters for a GMM:
%           * MODEL.Miu: a K-by-D matrix.
%           * MODEL.Sigma: a D-by-D-by-K matrix.
%           * MODEL.Pi: a 1-by-K vector.
% ============================================================

%% Generate Initial Centroids

    threshold = 1e-15;
    [N, D] = size(X);
 
    if isscalar(K_or_centroids)
        K = K_or_centroids;
        % randomly pick centroids
        rndp = randperm(N);
        centroids = X(rndp(1:K), :);
    else
        K = size(K_or_centroids, 1);
        centroids = K_or_centroids;
    end
 
%% Initial Values
    [pMiu pPi pSigma] = init_params();
 
    Lprev = -inf; % error of the last cluster
    
%% EM algorithm    
    while true
    % Estimate Step
        
        % add a small positve value to the diagnal
        % avoid inv warning
        for kdim = 1:K
            for idx = 1:size(pSigma, 1)
                pSigma(idx, idx, kdim) = pSigma(idx, idx, kdim) + (1e-5);
            end
        end
            
        Px = calc_prob();
        % new value for pGamma(N*k)
        % pGamma(i,k) = Xi is the probability generated by the kth Gaussian  
        pGamma = Px .* repmat(pPi, N, 1);
        pGamma = pGamma ./ repmat(sum(pGamma, 2), 1, K);
        %Denominator is pi(j) * N(xi | pMiu(j), sum up pSigma(j)) for all j
       
    % Maximization Step - through Maximize likelihood Estimation
        % new value for parameters of each Component
        % Nk(1*k): sum of all the samples prob. generated by the kth Gaussian
        % sum of NK is N
        Nk = sum(pGamma, 1); 

        % update pMiu
        pMiu = diag(1./Nk) * pGamma' * X;
        pPi = Nk/N;
        
        % update k pSigma
        for kk = 1:K
            Xshift = X-repmat(pMiu(kk, :), N, 1);
            pSigma(:, :, kk) = (Xshift' * ...
                (diag(pGamma(:, kk)) * Xshift)) / Nk(kk);
        end
 
        % check for convergence
        L = sum(log(Px*pPi'));
        if L-Lprev < threshold
            break;
        end
        Lprev = L;
    end
 
    if nargout == 1
        varargout = {Px};
    else
        model = [];
        model.Miu = pMiu;
        model.Sigma = pSigma;
        model.Pi = pPi;
        varargout = {Px, model};
    end
 
    %% Function Definition  
    function [pMiu pPi pSigma] = init_params()
        pMiu = centroids;
        pPi = zeros(1, K);
        pSigma = zeros(D, D, K);
 
        % hard assign x to each centroids
        % distance matrix
        %?x-pMiu?^2 = x^2+pMiu^2-2*x*Miu
        distmat = repmat(sum(X.*X, 2), 1, K) + ...
            repmat(sum(pMiu.*pMiu, 2)', N, 1) - ...
            2*X*pMiu';
        [dummy labels] = min(distmat, [], 2);
 
        for k=1:K
            Xk = X(labels == k, :);
            pPi(k) = size(Xk, 1)/N;
            pSigma(:, :, k) = cov(Xk);
        end
    end
 
    function Px = calc_prob()
        % Gaussian posterior probability   
        % N(x|pMiu,pSigma) = 1/((2pi)^(D/2))*(1/(abs(sigma))^0.5)*exp(-1/2*(x-pMiu)'pSigma^(-1)*(x-pMiu)) 
        Px = zeros(N, K);
        for k = 1:K
            Xshift = X-repmat(pMiu(k, :), N, 1);
            inv_pSigma = inv(pSigma(:, :, k));
            tmp = sum((Xshift*inv_pSigma) .* Xshift, 2);
            coef = (2*pi)^(-D/2) * sqrt(det(inv_pSigma));
            Px(:, k) = coef * exp(-0.5*tmp);
        end
    end
end